name: quit_vaping
description: AI-powered app to help users quit vaping through personalized tracking and support.
version: 1.0.0+33
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  intl: ^0.20.2
  flutter_local_notifications: ^19.3.1
  flutter_local_notifications_linux: ^6.0.0
  flutter_local_notifications_platform_interface: ^9.1.0
  shared_preferences: ^2.1.0
  path_provider: ^2.0.14
  flutter_svg: ^2.2.0
  fl_chart: ^1.0.0
  lottie: ^3.3.1
  url_launcher: ^6.1.10
  image_picker: ^1.1.2
  flutter_markdown: ^0.6.23
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^3.15.1
  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.3.9
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.1
  flutter_animate: ^4.1.1
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.0.2
  # Monetization packages
  in_app_purchase: ^3.1.11
  google_mobile_ads: ^6.0.0
  purchases_flutter: ^8.10.6
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  hive_generator: ^2.0.0
  freezed: ^3.1.0
  json_serializable: ^6.10.0
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - .env
    - .env.example
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#4CAF50"
  image: assets/images/splash_logo.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"