name: quit_vaping
description: A Flutter application to help users quit vaping.
publish_to: 'none'
version: 1.0.0+51

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  intl: ^0.18.1
  url_launcher: ^6.1.12
  package_info_plus: ^4.2.0
  uuid: ^3.0.7
  fl_chart: ^0.63.0
  google_fonts: ^5.1.0
  in_app_purchase: ^3.1.11
  google_mobile_ads: ^3.0.0
  just_audio: ^0.9.34

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/free_images/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
