name: quit_vaping
description: AI-powered app to help users quit vaping through personalized tracking and support.
version: 1.0.0+14  # Format
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  intl: ^0.18.0
  flutter_local_notifications: ^17.2.4
  flutter_local_notifications_linux: ^4.0.0+1
  flutter_local_notifications_platform_interface: ^7.0.0
  shared_preferences: ^2.1.0
  path_provider: ^2.0.14
  flutter_svg: ^2.0.5
  fl_chart: ^0.62.0
  lottie: ^2.3.2
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+4
  flutter_markdown: ^0.6.14
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.10.0
  firebase_analytics: ^10.2.1
  firebase_crashlytics: ^3.1.1
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  firebase_storage: ^11.1.1
  http: ^0.13.6
  connectivity_plus: ^3.0.6
  permission_handler: ^10.2.0
  flutter_animate: ^4.1.1
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.0.2
  # Monetization packages
  in_app_purchase: ^3.1.11
  google_mobile_ads: ^3.1.0
  purchases_flutter: ^6.0.0  # RevenueCat for subscription management
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - .env
    - .env.example
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#4CAF50"
  image: assets/images/splash_logo.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"